# Generated by Django 3.1.4 on 2021-01-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_items_data_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_data',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
