# Generated by Django 3.1.4 on 2021-01-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210102_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_data',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
